### ISSUE TITLE
Fix footer in blog route for mobile 

### ISSUE THREAD

**Issue by Sky-De** [techy1999/BlogFrontend#112]
### Current behavior
now if you navigate to the blog route in mobile device size, the footer hanging in the middle of the page

### Screens
![chrome-capture-2024-4-4](https://github.com/techy1999/BlogFrontend/assets/79264045/8a80d3f8-8cbc-412c-adb1-d3991511cc43)

![chrome-capture-2024-4-4](https://github.com/techy1999/BlogFrontend/assets/79264045/7b57723d-b0db-4281-a3b3-f39fb3f0d49c)

### Desired behavior
footer must stick to the end of the screen on those pages that do not have enough content to push down the footer 

![chrome-capture-2024-4-4 (1)](https://github.com/techy1999/BlogFrontend/assets/79264045/255e3ca8-915c-4cad-bd15-f80cd931d5d2)

### Consideration
entire app.js does not follow best practices that may cause difficulty in scaling the project later, 
please open a new issue for **refactoring the base structure of the app.js file and routing system**

**Comment by Sky-De** [comment]
@techy1999 please assign this to me, it's done and ready for PR already
thanks
also please open a new issue for refactoring the app.js and routing system and assign it to me
thanks

**Comment by techy1999** [comment]
@Sky-De  Assigned you.
