### ISSUE TITLE
Issue in Register forms UI

### ISSUE THREAD

**Issue by Sky-De** [techy1999/BlogFrontend#118]
### Issue
login and register forms have oversized titles and inputs that cause the form to stick to the top and bottom and need scrolls to display the entire form, also shadows of them are too much 

oversize title and input also heavy shadows are not aligned with material design principles 

![chrome-capture-2024-4-9 (1)](https://github.com/techy1999/BlogFrontend/assets/79264045/0980c55a-1ae9-4076-925e-94090dc3f7c1)
![chrome-capture-2024-4-9](https://github.com/techy1999/BlogFrontend/assets/79264045/917fc7c4-2f27-4622-aefa-47d8464b9078)

### What to do
1. improve the design and style of forms to be aligned with material design principles
2. make sure they responsive for all devices

**Comment by Sky-De** [comment]
@techy1999 hi, assign this to me, it will almost the last UI issue of your app for now, after that I will start to write tests for your application
for now please assign this to me 
thanks 
skyDe

**Comment by techy1999** [comment]
@Sky-De You can work on it for just fixing the issue in register page.

There are many important other features , that we have to do.
like 👎 
- When clicked on like, this should be a open snackbar (already implemented for logout)
- Design of card for blogs is not looking good 
-  We can a have loader when there is API call is happening
