### ISSUE TITLE
Design footer and add menus

### ISSUE THREAD

**Issue by sd8917** [techy1999/BlogFrontend#17]
# Footer
1. Add design
2. create footer with menu
3. social icon
4. menu itesm

Left side contain google map pinned location

> ABOUT US
> CONTACT US
> Brand Partners

> PRIVACY POLICY
> TERM CONDITION
> JOIN OUR TEAM

Down center we have social icons 
for facebook, youtube,linkdin, instagram

**Comment by techy1999** [comment]
Check [pr](https://github.com/techy1999/BlogFrontend/pull/55)
