### ISSUE TITLE
Create Home page design.

### ISSUE THREAD

**Issue by techy1999** [techy1999/BlogFrontend#3]
# :rocket: Create Home page design

- Design Some UI and put into the comment once verified start working on ticket -

**Comment by sd8917** [comment]
Create Home page ui UNDER #6 

![HOMEPAGE](https://github.com/techy1999/BlogFrontend/assets/34008023/66a14bf5-c9f5-45b7-a4ef-acc915e1dbb5)

**Comment by sd8917** [comment]
now closing it to work on #6
