### ISSUE TITLE
Add Logic of  Logout by going to profile page.

### ISSUE THREAD

**Issue by techy1999** [techy1999/BlogFrontend#83]
- Go to folder - components/headers/ 
- copy the logout function and paste in profile code
- check by logging out 
![test2223](https://github.com/techy1999/BlogFrontend/assets/116334237/22021e61-587f-45a3-adbc-7a8eb532377f)

**Comment by amir-mansoor** [comment]
Working on this issue

**Comment by amir-mansoor** [comment]
hy i complete this task and create a pull request u can check it

**Comment by techy1999** [comment]
Hi @amir-mansoor, Are you still working on it ,I have to close it by today.

**Comment by techy1999** [comment]
https://github.com/techy1999/BlogFrontend/pull/141
