### ISSUE TITLE
Check Home page mobile responsiveness

### ISSUE THREAD

**Issue by techy1999** [techy1999/BlogFrontend#91]
- Issue reported by @Sky-De  
- [Comment](https://github.com/techy1999/BlogFrontend/pull/90#issue-2269330981)

**Comment by Sky-De** [comment]
@techy1999 assign this to me, i will fix that immediately
Thanks

**Comment by Sky-De** [comment]
@techy1999 this issue is fixed and it is ready for PR, if you still working on this project let me know by assignment , then i will create PR, thanks

**Comment by techy1999** [comment]
Hi @Sky-De Are you still working on it ,I have to close it by today.

**Comment by Sky-De** [comment]
> Hi @Sky-De Are you still working on it ,I have to close it by today.

It was done , i was waiting for your response, I'm going to create a PR right away

**Comment by techy1999** [comment]
changes are deployed,so closing it.https://github.com/techy1999/BlogFrontend/pull/105
